# -*- coding: utf-8 -*-
"""NaasNour_CryptoChatbot_Week1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kied47hQfET7GH8ekYwHVs6s5iJQDR-6
"""

print("👋 Hi, I’m NaasNour, your friendly crypto sidekick! 🌟")
print("Ask me about trending or sustainable cryptocurrencies, and I’ll guide you like a pro!")

crypto_db = {
    "Bitcoin": {
        "price_trend": "rising",
        "market_cap": "high",
        "energy_use": "high",
        "sustainability_score": 3/10
    },
    "Ethereum": {
        "price_trend": "stable",
        "market_cap": "high",
        "energy_use": "medium",
        "sustainability_score": 6/10
    },
    "Cardano": {
        "price_trend": "rising",
        "market_cap": "medium",
        "energy_use": "low",
        "sustainability_score": 8/10
    }
}

user_query = input("What would you like to know about crypto today? 💬\n").lower()

# Analyze the user's query and respond
if "sustainable" in user_query or "green" in user_query:
    recommend = max(crypto_db, key=lambda x: crypto_db[x]["sustainability_score"])
    print(f"🌱 You should check out {recommend}! It’s energy-efficient and built for the long haul.")

elif "trending" in user_query or "growth" in user_query or "rising" in user_query:
    trending_cryptos = [coin for coin, data in crypto_db.items() if data["price_trend"] == "rising"]
    print(f"🚀 These cryptos are on the rise: {', '.join(trending_cryptos)}. Worth keeping an eye on!")

elif "long-term" in user_query or "investment" in user_query:
    for coin, data in crypto_db.items():
        if data["price_trend"] == "rising" and data["market_cap"] == "high":
            print(f"📈 For long-term growth, {coin} looks promising with strong market performance.")
            break

else:
    print("🤔 Hmm, I’m not sure how to help with that yet. Try asking about trending or sustainable cryptos!")

print("👋 Hi, I’m NaasNour, your friendly crypto sidekick! 🌟")
print("Ask me about trending or sustainable cryptocurrencies, and I’ll guide you like a pro!")

crypto_db = {
    "Bitcoin": {
        "price_trend": "rising",
        "market_cap": "high",
        "energy_use": "high",
        "sustainability_score": 3/10
    },
    "Ethereum": {
        "price_trend": "stable",
        "market_cap": "high",
        "energy_use": "medium",
        "sustainability_score": 6/10
    },
    "Cardano": {
        "price_trend": "rising",
        "market_cap": "medium",
        "energy_use": "low",
        "sustainability_score": 8/10
    }
}

user_query = input("\n💬 What would you like to know about crypto today?\n").lower()

if "sustainable" in user_query or "green" in user_query:
    recommend = max(crypto_db, key=lambda x: crypto_db[x]["sustainability_score"])
    print(f"🌱 You should check out {recommend}! It’s energy-efficient and built for the long haul.")

elif "trending" in user_query or "growth" in user_query or "rising" in user_query:
    trending_cryptos = [coin for coin, data in crypto_db.items() if data["price_trend"] == "rising"]
    print(f"🚀 These cryptos are on the rise: {', '.join(trending_cryptos)}. Worth keeping an eye on!")

elif "long-term" in user_query or "investment" in user_query:
    for coin, data in crypto_db.items():
        if data["price_trend"] == "rising" and data["market_cap"] == "high":
            print(f"📈 For long-term growth, {coin} looks promising with strong market performance.")
            break

else:
    print("🤔 Hmm, I’m not sure how to help with that yet. Try asking about trending or sustainable cryptos!")

    print("\n📌 Reminder: Cryptocurrency investments are risky. Always do your own research before making decisions.")